id: PA48BF601
initial_creation_type: input
source_metadata:
  title: Nyoshul Khenpo Jamyang Dorje
  language: en
  description: 'Texts by the great Dzogchen teacher and historian Nyoshul Khenpo Jamyang
    Dorje (smyo shul mkhan po ''jam dbyangs rdo rje, 1932–1999):'
  volume:
    7dc817a4a2bc46f6a385227ebb6c284f:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Calling the Guru from Afar
    b52c60e1557a490f9321a87abf8b65a6:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    9a0b4aea32034d1aa1b122c3b9acbd86:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Dzogchen
    4e76d47279024caaaef57541677545e9:
      title: The Five Wisdoms
      parent: Dzogchen
    f5e31aac358f4a8f9f536efe90b2ed6a:
      title: Prayer to the Omniscient Longchen Rabjam
      parent: Lineage Prayers
    dd4f0e506e564582a71ea526e9f01e9b:
      title: 'Mindfulness: The Mirror of the Mind'
      parent: Poems
    0d26eaad818b40d09651077091a41838:
      title: Natural Great Peace
      parent: Poems
created_at: '2022-03-01T01:05:41.715003'
last_modified_at: '2022-03-01T01:05:41.715009'
